import type { MineralWaterComposition } from "./minerals";

export interface MineralWater {
  name: string;
  composition: MineralWaterComposition;
}

export const DEFAULT_WATER_NAME = "Acqua Panna";

export const MINERAL_WATERS = [
  {
    name: "Acqua Panna",
    composition: {
      calcium: 30.2,
      magnesium: 6.9,
      sodium: 6.5,
      potassium: 0.9,
      bicarbonate: 100,
      sulfate: 21.4,
      chloride: 7.1,
      nitrate: 5.7,
    },
  },
  {
    name: "Antipodes",
    composition: {
      calcium: 3.5,
      magnesium: 1.8,
      sodium: 11,
      potassium: 3.3,
      bicarbonate: 35,
      sulfate: 4.5,
      chloride: 7,
      nitrate: 1.5,
    },
  },
  {
    name: "Apollinaris",
    composition: {
      calcium: 100,
      magnesium: 130,
      sodium: 410,
      potassium: 20,
      bicarbonate: 1810,
      sulfate: 80,
      chloride: 100,
      nitrate: 1.6,
    },
  },
  {
    name: "Aquarel Birken",
    composition: {
      calcium: 106,
      magnesium: 23.3,
      sodium: 19.7,
      potassium: 0,
      bicarbonate: 423,
      sulfate: 0,
      chloride: 32.2,
      nitrate: 0,
    },
  },
  {
    name: "Badoit",
    composition: {
      calcium: 190,
      magnesium: 85,
      sodium: 165,
      potassium: 10,
      bicarbonate: 1300,
      sulfate: 38,
      chloride: 44,
      nitrate: 0,
    },
  },
  {
    name: "Borsec",
    composition: {
      calcium: 317.5,
      magnesium: 106.6,
      sodium: 76.6,
      potassium: 12,
      bicarbonate: 1660,
      sulfate: 22.2,
      chloride: 20.5,
      nitrate: 0,
    },
  },
  {
    name: "Cana",
    composition: {
      calcium: 340,
      magnesium: 33,
      sodium: 9,
      potassium: 2,
      bicarbonate: 1100,
      sulfate: 86,
      chloride: 2,
      nitrate: 0.2,
    },
  },
  {
    name: "Calistoga",
    composition: {
      calcium: 3.6,
      magnesium: 0,
      sodium: 170,
      potassium: 14,
      bicarbonate: 22,
      sulfate: 110,
      chloride: 210,
      nitrate: 0,
    },
  },
  {
    name: "Calistoga Premium",
    composition: {
      calcium: 4.5,
      magnesium: 2,
      sodium: 41,
      potassium: 6.4,
      bicarbonate: 56,
      sulfate: 21,
      chloride: 41,
      nitrate: 0,
    },
  },
  {
    name: "Carola Rouge",
    composition: {
      calcium: 103,
      magnesium: 52.2,
      sodium: 103,
      potassium: 22.2,
      bicarbonate: 505,
      sulfate: 205,
      chloride: 76.6,
      nitrate: 0,
    },
  },
  {
    name: "Contrex",
    composition: {
      calcium: 468,
      magnesium: 74.5,
      sodium: 9.4,
      potassium: 3.2,
      bicarbonate: 372,
      sulfate: 1121,
      chloride: 10,
      nitrate: 2.9,
    },
  },
  {
    name: "Coralba",
    composition: {
      calcium: 54,
      magnesium: 21,
      sodium: 0.4,
      potassium: 0.3,
      bicarbonate: 255,
      sulfate: 8.6,
      chloride: 0.8,
      nitrate: 2,
    },
  },
  {
    name: "Dorna",
    composition: {
      calcium: 287.1,
      magnesium: 8.61,
      sodium: 23.5,
      potassium: 2.7,
      bicarbonate: 0,
      sulfate: 25.5,
      chloride: 10.9,
      nitrate: 1.66,
    },
  },
  {
    name: "Evian",
    composition: {
      calcium: 78,
      magnesium: 24,
      sodium: 5,
      potassium: 1,
      bicarbonate: 357,
      sulfate: 10,
      chloride: 4.5,
      nitrate: 3.8,
    },
  },
  {
    name: "Farris",
    composition: {
      calcium: 26,
      magnesium: 30,
      sodium: 400,
      potassium: 0,
      bicarbonate: 300,
      sulfate: 15,
      chloride: 590,
      nitrate: 0,
    },
  },
  {
    name: "Fiuggi",
    composition: {
      calcium: 15.9,
      magnesium: 6.3,
      sodium: 6.4,
      potassium: 4.4,
      bicarbonate: 81.7,
      sulfate: 6,
      chloride: 13.9,
      nitrate: 7,
    },
  },
  {
    name: "Gerolsteiner",
    composition: {
      calcium: 348,
      magnesium: 108,
      sodium: 118,
      potassium: 10.8,
      bicarbonate: 1816,
      sulfate: 38.3,
      chloride: 39.7,
      nitrate: 5.1,
    },
  },
  {
    name: "Harghita",
    composition: {
      calcium: 113.4,
      magnesium: 69.4,
      sodium: 68.3,
      potassium: 11.1,
      bicarbonate: 854,
      sulfate: 0,
      chloride: 2,
      nitrate: 0,
    },
  },
  {
    name: "Hassia Sprudel",
    composition: {
      calcium: 190,
      magnesium: 34,
      sodium: 197,
      potassium: 21.9,
      bicarbonate: 1098,
      sulfate: 37,
      chloride: 109,
      nitrate: 0,
    },
  },
  {
    name: "Henniez",
    composition: {
      calcium: 106,
      magnesium: 19,
      sodium: 7,
      potassium: 1,
      bicarbonate: 392,
      sulfate: 13,
      chloride: 8,
      nitrate: 16,
    },
  },
  {
    name: "Kessel",
    composition: {
      calcium: 40.8,
      magnesium: 13.3,
      sodium: 770.4,
      potassium: 5.4,
      bicarbonate: 2123,
      sulfate: 5.35,
      chloride: 97.4,
      nitrate: 0.1,
    },
  },
  {
    name: "Mountain Valley Spring",
    composition: {
      calcium: 68,
      magnesium: 8,
      sodium: 2.8,
      potassium: 1,
      bicarbonate: 238,
      sulfate: 9.72,
      chloride: 0,
      nitrate: 0,
    },
  },
  {
    name: "Neuselters",
    composition: {
      calcium: 100,
      magnesium: 27,
      sodium: 90,
      potassium: 6,
      bicarbonate: 570,
      sulfate: 6,
      chloride: 60,
      nitrate: 0,
    },
  },
  {
    name: "Paradi",
    composition: {
      calcium: 174,
      magnesium: 50,
      sodium: 470,
      potassium: 12,
      bicarbonate: 1780,
      sulfate: 144,
      chloride: 47,
      nitrate: 0,
    },
  },
  {
    name: "Perrier",
    composition: {
      calcium: 147.3,
      magnesium: 3.4,
      sodium: 9,
      potassium: 0.6,
      bicarbonate: 390,
      sulfate: 33,
      chloride: 21.5,
      nitrate: 18,
    },
  },
  {
    name: "PurPur",
    composition: {
      calcium: 24,
      magnesium: 7.3,
      sodium: 25.6,
      potassium: 5.6,
      bicarbonate: 151,
      sulfate: 28.5,
      chloride: 1.8,
      nitrate: 0,
    },
  },
  {
    name: "Radenska",
    composition: {
      calcium: 230,
      magnesium: 79,
      sodium: 520,
      potassium: 79,
      bicarbonate: 2100,
      sulfate: 100,
      chloride: 69,
      nitrate: 2.2,
    },
  },
  {
    name: "Rosbacher Klassich",
    composition: {
      calcium: 206,
      magnesium: 100,
      sodium: 72.7,
      potassium: 4.4,
      bicarbonate: 1095,
      sulfate: 19,
      chloride: 112,
      nitrate: 0,
    },
  },
  {
    name: "Saint-Yorre",
    composition: {
      calcium: 78.8,
      magnesium: 9,
      sodium: 1744,
      potassium: 115,
      bicarbonate: 4263,
      sulfate: 182,
      chloride: 329,
      nitrate: 0,
    },
  },
  {
    name: "Salvus",
    composition: {
      calcium: 99,
      magnesium: 5.7,
      sodium: 18.5,
      potassium: 1,
      bicarbonate: 211,
      sulfate: 69,
      chloride: 42.4,
      nitrate: 0,
    },
  },
  {
    name: "San Benedetto",
    composition: {
      calcium: 46,
      magnesium: 30,
      sodium: 6.8,
      potassium: 1.1,
      bicarbonate: 293,
      sulfate: 4.9,
      chloride: 2.8,
      nitrate: 6.8,
    },
  },
  {
    name: "San Narciso",
    composition: {
      calcium: 55,
      magnesium: 9,
      sodium: 1138,
      potassium: 53.4,
      bicarbonate: 2196,
      sulfate: 54,
      chloride: 596,
      nitrate: 0,
    },
  },
  {
    name: "San Pellegrino",
    composition: {
      calcium: 208.08,
      magnesium: 56.9,
      sodium: 44.6,
      potassium: 3.7,
      bicarbonate: 220.6,
      sulfate: 549.2,
      chloride: 74.3,
      nitrate: 1.5,
    },
  },
  {
    name: "Tesanjski Diamond",
    composition: {
      calcium: 64.92,
      magnesium: 47.62,
      sodium: 15,
      potassium: 0.78,
      bicarbonate: 429,
      sulfate: 34,
      chloride: 9,
      nitrate: 0.88,
    },
  },
  {
    name: "Topo Chico",
    composition: {
      calcium: 29,
      magnesium: 9,
      sodium: 35,
      potassium: 0,
      bicarbonate: 115,
      sulfate: 40,
      chloride: 35,
      nitrate: 0,
    },
  },
  {
    name: "Ty Nant",
    composition: {
      calcium: 22.5,
      magnesium: 11.5,
      sodium: 22,
      potassium: 1,
      bicarbonate: 116,
      sulfate: 3.7,
      chloride: 14,
      nitrate: 0,
    },
  },
  {
    name: "Vittel",
    composition: {
      calcium: 202,
      magnesium: 36,
      sodium: 3.8,
      potassium: 0,
      bicarbonate: 402,
      sulfate: 306,
      chloride: 0,
      nitrate: 0,
    },
  },
  {
    name: "Volvic",
    composition: {
      calcium: 11.5,
      magnesium: 8,
      sodium: 11.6,
      potassium: 6.2,
      bicarbonate: 71,
      sulfate: 6.9,
      chloride: 13.5,
      nitrate: 6.3,
    },
  },
  {
    name: "Voss",
    composition: {
      calcium: 3.46,
      magnesium: 0.78,
      sodium: 0,
      potassium: 0,
      bicarbonate: 0,
      sulfate: 5,
      chloride: 0,
      nitrate: 0,
    },
  },
  {
    name: "Waiwera",
    composition: {
      calcium: 12,
      magnesium: 2.6,
      sodium: 1.6,
      potassium: 0,
      bicarbonate: 20,
      sulfate: 0,
      chloride: 30,
      nitrate: 0,
    },
  },
  {
    name: "Saratoga",
    composition: {
      calcium: 5.5,
      magnesium: 1.1,
      sodium: 2.1,
      potassium: 0,
      bicarbonate: 11.3,
      sulfate: 4.5,
      chloride: 5.9,
      nitrate: 0.42,
    },
  },
  {
    name: "Agua De Piedra",
    composition: {
      calcium: 220,
      magnesium: 72,
      sodium: 48,
      potassium: 0,
      bicarbonate: 290,
      sulfate: 220,
      chloride: 70,
      nitrate: 0.009,
    },
  },
  {
    name: "Balbin",
    composition: {
      calcium: 70,
      magnesium: 23,
      sodium: 27,
      potassium: 4,
      bicarbonate: 346,
      sulfate: 55,
      chloride: 4,
      nitrate: 3,
    },
  },
] as const satisfies MineralWater[];

export const TapWaters: Record<string, MineralWater> = {
  Seattle: {
    name: "Seattle",
    composition: {
      calcium: 17.0,
      magnesium: 1.0,
      sodium: 4.0,
      potassium: 0.2,
      bicarbonate: 18.0,
      sulfate: 2.0,
      chloride: 3.5,
      nitrate: 0,
    },
  },
};

export const DEFAULT_TARGET =
  MINERAL_WATERS.at(0);
